class TurkeyCities {
  static const Map<String, List<String>> citiesAndDistricts = {
    'Adana': ['Merkez', 'Aladağ', 'Ceyhan', 'Feke', 'Karai̇sali', 'Karataş', 'Kozan', 'Pozanti', 'Sai̇mbeyli̇', 'Sariçam', 'Seyhan', 'Tufanbeyli̇', 'Yumurtalik', 'Yüreği̇r', 'Çukurova', 'İmamoğlu'],
    'Adiyaman': ['Merkez', 'Besni̇', 'Gerger', 'Gölbaşi', 'Kahta', 'Samsat', 'Si̇nci̇k', 'Tut', 'Çeli̇khan'],
    'Afyonkarahi̇sar': ['Merkez', 'Bayat', 'Başmakçi', 'Bolvadi̇n', 'Dazkiri', 'Di̇nar', 'Emi̇rdağ', 'Evci̇ler', 'Hocalar', 'Kizilören', 'Sandikli', 'Si̇nanpaşa', 'Sultandaği', 'Çay', 'Çobanlar', 'İhsani̇ye', 'İscehi̇sar', 'Şuhut'],
    'Aksaray': ['Merkez', 'Ağaçören', 'Eski̇l', 'Gülağaç', 'Güzelyurt', 'Ortaköy', 'Sariyahşi̇'],
    'Amasya': ['Merkez', 'Göynücek', 'Gümüşhaciköy', 'Hamamözü', 'Merzi̇fon', 'Suluova', 'Taşova'],
    'Ankara': ['Merkez', 'Akyurt', 'Altindağ', 'Ayaş', 'Bala', 'Beypazari', 'Elmadağ', 'Eti̇mesgut', 'Evren', 'Gölbaşi', 'Güdül', 'Haymana', 'Kaleci̇k', 'Kazan', 'Keçi̇ören', 'Kizilcahamam', 'Mamak', 'Nallihan', 'Polatli', 'Pursaklar', 'Si̇ncan', 'Yeni̇mahalle', 'Çamlidere', 'Çankaya', 'Çubuk', 'Şerefli̇koçhi̇sar'],
    'Antalya': ['Merkez', 'Akseki̇', 'Aksu', 'Alanya', 'Demre', 'Döşemealti', 'Elmali', 'Fi̇ni̇ke', 'Gazi̇paşa', 'Gündoğmuş', 'Kaş', 'Kemer', 'Kepez', 'Konyaalti', 'Korkuteli̇', 'Kumluca', 'Manavgat', 'Muratpaşa', 'Seri̇k', 'İbradi'],
    'Ardahan': ['Merkez', 'Damal', 'Göle', 'Hanak', 'Posof', 'Çildir'],
    'Artvi̇n': ['Merkez', 'Ardanuç', 'Arhavi̇', 'Borçka', 'Hopa', 'Murgul', 'Yusufeli̇', 'Şavşat'],
    'Aydin': ['Merkez', 'Bozdoğan', 'Buharkent', 'Di̇di̇m', 'Efeler', 'Germenci̇k', 'Karacasu', 'Karpuzlu', 'Koçarli', 'Kuyucak', 'Kuşadasi', 'Köşk', 'Nazi̇lli̇', 'Sultanhi̇sar', 'Söke', 'Yeni̇pazar', 'Çi̇ne', 'İnci̇rli̇ova'],
    'Ağri': ['Merkez', 'Di̇yadi̇n', 'Doğubayazit', 'Eleşki̇rt', 'Hamur', 'Patnos', 'Taşliçay', 'Tuta'],
    'Balikesi̇r': ['Merkez', 'Altieylül', 'Ayvalik', 'Balya', 'Bandirma', 'Bi̇gadi̇ç', 'Burhani̇ye', 'Dursunbey', 'Edremi̇t', 'Erdek', 'Gömeç', 'Gönen', 'Havran', 'Karesi̇', 'Kepsut', 'Manyas', 'Marmara', 'Savaştepe', 'Sindirgi', 'Susurluk', 'İvri̇ndi̇'],
    'Bartin': ['Merkez', 'Amasra', 'Kurucaşi̇le', 'Ulus'],
    'Batman': ['Merkez', 'Beşi̇ri̇', 'Gercüş', 'Hasankeyf', 'Kozluk', 'Sason'],
    'Bayburt': ['Merkez', 'Aydintepe', 'Demi̇rözü'],
    'Bi̇leci̇k': ['Merkez', 'Bozüyük', 'Gölpazari', 'Osmaneli̇', 'Pazaryeri̇', 'Söğüt', 'Yeni̇pazar', 'İnhi̇sar'],
    'Bi̇ngöl': ['Merkez', 'Adakli', 'Genç', 'Karliova', 'Ki̇ği', 'Solhan', 'Yayladere', 'Yedi̇su'],
    'Bi̇tli̇s': ['Merkez', 'Adi̇lcevaz', 'Ahlat', 'Güroymak', 'Hi̇zan', 'Mutki̇', 'Tatvan'],
    'Bolu': ['Merkez', 'Dörtdi̇van', 'Gerede', 'Göynük', 'Kibriscik', 'Mengen', 'Mudurnu', 'Seben', 'Yeni̇çağa'],
    'Burdur': ['Merkez', 'Altinyayla', 'Ağlasun', 'Bucak', 'Gölhi̇sar', 'Karamanli', 'Kemer', 'Tefenni̇', 'Yeşi̇lova', 'Çavdir', 'Çelti̇kçi̇'],
    'Bursa': ['Merkez', 'Büyükorhan', 'Gemli̇k', 'Gürsu', 'Harmancik', 'Karacabey', 'Keles', 'Kestel', 'Mudanya', 'Mustafakemalpaşa', 'Ni̇lüfer', 'Orhaneli̇', 'Orhangazi̇', 'Osmangazi̇', 'Yeni̇şehi̇r', 'Yildirim', 'İnegöl', 'İzni̇k'],
    'Deni̇zli̇': ['Merkez', 'Acipayam', 'Babadağ', 'Baklan', 'Beki̇lli̇', 'Beyağaç', 'Bozkurt', 'Buldan', 'Güney', 'Honaz', 'Kale', 'Merkezefendi̇', 'Pamukkale', 'Sarayköy', 'Seri̇nhi̇sar', 'Tavas', 'Çal', 'Çameli̇', 'Çardak', 'Çi̇vri̇l'],
    'Di̇yarbakir': ['Merkez', 'Bağlar', 'Bi̇smi̇l', 'Di̇cle', 'Ergani̇', 'Eği̇l', 'Hani̇', 'Hazro', 'Kayapinar', 'Kocaköy', 'Kulp', 'Li̇ce', 'Si̇lvan', 'Sur', 'Yeni̇şehi̇r', 'Çermi̇k', 'Çinar', 'Çüngüş'],
    'Düzce': ['Merkez', 'Akçakoca', 'Cumayeri̇', 'Gölyaka', 'Gümüşova', 'Kaynaşli', 'Yiğilca', 'Çi̇li̇mli̇'],
    'Edi̇rne': ['Merkez', 'Enez', 'Havsa', 'Keşan', 'Lalapaşa', 'Meri̇ç', 'Süloğlu', 'Uzunköprü', 'İpsala'],
    'Elaziğ': ['Merkez', 'Alacakaya', 'Aricak', 'Ağin', 'Baski̇l', 'Karakoçan', 'Keban', 'Kovancilar', 'Maden', 'Palu', 'Si̇vri̇ce'],
    'Erzi̇ncan': ['Merkez', 'Kemah', 'Kemali̇ye', 'Otlukbeli̇', 'Refahi̇ye', 'Tercan', 'Çayirli', 'Üzümlü', 'İli̇ç'],
    'Erzurum': ['Merkez', 'Azi̇zi̇ye', 'Aşkale', 'Hinis', 'Horasan', 'Karayazi', 'Karaçoban', 'Köprüköy', 'Narman', 'Oltu', 'Olur', 'Palandöken', 'Pasi̇nler', 'Pazaryolu', 'Tekman', 'Tortum', 'Uzundere', 'Yakuti̇ye', 'Çat', 'İspi̇r', 'Şenkaya'],
    'Eski̇şehi̇r': ['Merkez', 'Alpu', 'Beyli̇kova', 'Günyüzü', 'Han', 'Mahmudi̇ye', 'Mi̇halgazi̇', 'Mi̇haliççik', 'Odunpazari', 'Saricakaya', 'Seyi̇tgazi̇', 'Si̇vri̇hi̇sar', 'Tepebaşi', 'Çi̇fteler', 'İnönü'],
    'Gazi̇antep': ['Merkez', 'Araban', 'Karkamiş', 'Ni̇zi̇p', 'Nurdaği', 'Oğuzeli̇', 'Yavuzeli̇', 'İslahi̇ye', 'Şahi̇nbey', 'Şehi̇tkami̇l'],
    'Gi̇resun': ['Merkez', 'Alucra', 'Bulancak', 'Dereli̇', 'Doğankent', 'Espi̇ye', 'Eynesi̇l', 'Görele', 'Güce', 'Keşap', 'Pi̇razi̇z', 'Ti̇rebolu', 'Yağlidere', 'Çamoluk', 'Çanakçi', 'Şebi̇nkarahi̇sar'],
    'Gümüşhane': ['Merkez', 'Kelki̇t', 'Köse', 'Kürtün', 'Torul', 'Şi̇ran'],
    'Hakkari̇': ['Merkez', 'Yüksekova', 'Çukurca', 'Şemdi̇nli̇'],
    'Hatay': ['Merkez', 'Altinözü', 'Antakya', 'Arsuz', 'Belen', 'Defne', 'Dörtyol', 'Erzi̇n', 'Hassa', 'Kirikhan', 'Kumlu', 'Payas', 'Reyhanli', 'Samandağ', 'Yayladaği', 'İskenderun'],
    'Isparta': ['Merkez', 'Aksu', 'Atabey', 'Eği̇rdi̇r', 'Gelendost', 'Gönen', 'Keçi̇borlu', 'Seni̇rkent', 'Sütçüler', 'Uluborlu', 'Yalvaç', 'Yeni̇şarbademli̇', 'Şarki̇karaağaç'],
    'Iğdir': ['Merkez', 'Aralik', 'Karakoyunlu', 'Tuzluca'],
    'Kahramanmaraş': ['Merkez', 'Afşi̇n', 'Andirin', 'Dulkadi̇roğlu', 'Eki̇nözü', 'Elbi̇stan', 'Göksun', 'Nurhak', 'Oni̇ki̇şubat', 'Pazarcik', 'Türkoğlu', 'Çağlayanceri̇t'],
    'Karabük': ['Merkez', 'Eflani̇', 'Eski̇pazar', 'Ovacik', 'Safranbolu', 'Yeni̇ce'],
    'Karaman': ['Merkez', 'Ayranci', 'Başyayla', 'Ermenek', 'Kazimkarabeki̇r', 'Sariveli̇ler'],
    'Kars': ['Merkez', 'Akyaka', 'Arpaçay', 'Di̇gor', 'Kağizman', 'Sarikamiş', 'Seli̇m', 'Susuz'],
    'Kastamonu': ['Merkez', 'Abana', 'Araç', 'Azdavay', 'Ağli', 'Bozkurt', 'Ci̇de', 'Daday', 'Devrekani̇', 'Doğanyurt', 'Hanönü', 'Küre', 'Pinarbaşi', 'Seydi̇ler', 'Taşköprü', 'Tosya', 'Çatalzeyti̇n', 'İhsangazi̇', 'İnebolu', 'Şenpazar'],
    'Kayseri̇': ['Merkez', 'Akkişla', 'Bünyan', 'Develi̇', 'Felahi̇ye', 'Hacilar', 'Kocasi̇nan', 'Meli̇kgazi̇', 'Pinarbaşi', 'Sarioğlan', 'Sariz', 'Talas', 'Tomarza', 'Yahyali', 'Yeşi̇lhi̇sar', 'Özvatan', 'İncesu'],
    'Kirikkale': ['Merkez', 'Bahşi̇li̇', 'Balişeyh', 'Deli̇ce', 'Karakeçi̇li̇', 'Keski̇n', 'Sulakyurt', 'Yahşi̇han', 'Çelebi̇'],
    'Kirklareli̇': ['Merkez', 'Babaeski̇', 'Demi̇rköy', 'Kofçaz', 'Lüleburgaz', 'Pehli̇vanköy', 'Pinarhi̇sar', 'Vi̇ze'],
    'Kirşehi̇r': ['Merkez', 'Akpinar', 'Akçakent', 'Boztepe', 'Kaman', 'Mucur', 'Çi̇çekdaği'],
    'Ki̇li̇s': ['Merkez', 'Elbeyli̇', 'Musabeyli̇', 'Polateli̇'],
    'Kocaeli̇': ['Merkez', 'Başi̇skele', 'Darica', 'Deri̇nce', 'Di̇lovasi', 'Gebze', 'Gölcük', 'Kandira', 'Karamürsel', 'Kartepe', 'Körfez', 'Çayirova', 'İzmi̇t'],
    'Konya': ['Merkez', 'Ahirli', 'Akören', 'Akşehi̇r', 'Altineki̇n', 'Beyşehi̇r', 'Bozkir', 'Ci̇hanbeyli̇', 'Derbent', 'Derebucak', 'Doğanhi̇sar', 'Emi̇rgazi̇', 'Ereğli̇', 'Güneysinir', 'Hadi̇m', 'Halkapinar', 'Hüyük', 'Ilgin', 'Kadinhani', 'Karapinar', 'Karatay', 'Kulu', 'Meram', 'Sarayönü', 'Selçuklu', 'Seydi̇şehi̇r', 'Taşkent', 'Tuzlukçu', 'Yalihüyük', 'Yunak', 'Çelti̇k', 'Çumra'],
    'Kütahya': ['Merkez', 'Altintaş', 'Aslanapa', 'Domani̇ç', 'Dumlupinar', 'Emet', 'Gedi̇z', 'Hi̇sarcik', 'Pazarlar', 'Si̇mav', 'Tavşanli', 'Çavdarhi̇sar', 'Şaphane'],
    'Malatya': ['Merkez', 'Akçadağ', 'Arapgi̇r', 'Arguvan', 'Battalgazi̇', 'Darende', 'Doğanyol', 'Doğanşehi̇r', 'Heki̇mhan', 'Kale', 'Kuluncak', 'Pütürge', 'Yazihan', 'Yeşi̇lyurt'],
    'Mani̇sa': ['Merkez', 'Ahmetli̇', 'Akhi̇sar', 'Alaşehi̇r', 'Demi̇rci̇', 'Gölmarmara', 'Gördes', 'Kirkağaç', 'Kula', 'Köprübaşi', 'Sali̇hli̇', 'Sarigöl', 'Saruhanli', 'Selendi̇', 'Soma', 'Turgutlu', 'Yunusemre', 'Şehzadeler'],
    'Mardi̇n': ['Merkez', 'Artuklu', 'Dargeçi̇t', 'Deri̇k', 'Kiziltepe', 'Mazidaği', 'Mi̇dyat', 'Nusaybi̇n', 'Savur', 'Yeşi̇lli̇', 'Ömerli̇'],
    'Mersi̇n': ['Merkez', 'Akdeni̇z', 'Anamur', 'Aydincik', 'Bozyazi', 'Erdemli̇', 'Gülnar', 'Mezi̇tli̇', 'Mut', 'Si̇li̇fke', 'Tarsus', 'Toroslar', 'Yeni̇şehi̇r', 'Çamliyayla'],
    'Muğla': ['Merkez', 'Bodrum', 'Dalaman', 'Datça', 'Fethi̇ye', 'Kavaklidere', 'Köyceği̇z', 'Marmari̇s', 'Menteşe', 'Mi̇las', 'Ortaca', 'Seydi̇kemer', 'Ula', 'Yatağan'],
    'Muş': ['Merkez', 'Bulanik', 'Hasköy', 'Korkut', 'Malazgi̇rt', 'Varto'],
    'Nevşehi̇r': ['Merkez', 'Acigöl', 'Avanos', 'Deri̇nkuyu', 'Gülşehi̇r', 'Hacibektaş', 'Kozakli', 'Ürgüp'],
    'Ni̇ğde': ['Merkez', 'Altunhi̇sar', 'Bor', 'Ulukişla', 'Çamardi', 'Çi̇ftli̇k'],
    'Ordu': ['Merkez', 'Akkuş', 'Aybasti', 'Fatsa', 'Gölköy', 'Gülyali', 'Gürgentepe', 'Kabadüz', 'Kabataş', 'Korgan', 'Kumru', 'Mesudi̇ye', 'Perşembe', 'Ulubey', 'Çamaş', 'Çatalpinar', 'Çaybaşi', 'Ünye', 'İki̇zce'],
    'Osmani̇ye': ['Merkez', 'Bahçe', 'Düzi̇çi̇', 'Hasanbeyli̇', 'Kadi̇rli̇', 'Sumbas', 'Toprakkale'],
    'Ri̇ze': ['Merkez', 'Ardeşen', 'Derepazari', 'Findikli', 'Güneysu', 'Hemşi̇n', 'Kalkandere', 'Pazar', 'Çamlihemşi̇n', 'Çayeli̇', 'İki̇zdere', 'İyi̇dere'],
    'Sakarya': ['Merkez', 'Adapazari', 'Akyazi', 'Ari̇fi̇ye', 'Erenler', 'Feri̇zli̇', 'Geyve', 'Hendek', 'Karapürçek', 'Karasu', 'Kaynarca', 'Kocaali̇', 'Pamukova', 'Sapanca', 'Serdi̇van', 'Söğütlü', 'Tarakli'],
    'Samsun': ['Merkez', 'Alaçam', 'Asarcik', 'Atakum', 'Ayvacik', 'Bafra', 'Cani̇k', 'Havza', 'Kavak', 'Ladi̇k', 'Ondokuzmayis', 'Salipazari', 'Tekkeköy', 'Terme', 'Vezi̇rköprü', 'Yakakent', 'Çarşamba', 'İlkadim'],
    'Si̇i̇rt': ['Merkez', 'Aydinlar', 'Baykan', 'Eruh', 'Kurtalan', 'Pervari̇', 'Şi̇rvan'],
    'Si̇nop': ['Merkez', 'Ayancik', 'Boyabat', 'Di̇kmen', 'Durağan', 'Erfelek', 'Gerze', 'Saraydüzü', 'Türkeli̇'],
    'Si̇vas': ['Merkez', 'Akincilar', 'Altinyayla', 'Di̇vri̇ği̇', 'Doğanşar', 'Gemerek', 'Gölova', 'Gürün', 'Hafi̇k', 'Kangal', 'Koyulhi̇sar', 'Suşehri̇', 'Ulaş', 'Yildizeli̇', 'Zara', 'İmranli', 'Şarkişla'],
    'Teki̇rdağ': ['Merkez', 'Ergene', 'Hayrabolu', 'Kapakli', 'Malkara', 'Marmaraereğli̇si̇', 'Muratli', 'Saray', 'Süleymanpaşa', 'Çerkezköy', 'Çorlu', 'Şarköy'],
    'Tokat': ['Merkez', 'Almus', 'Artova', 'Başçi̇ftli̇k', 'Erbaa', 'Ni̇ksar', 'Pazar', 'Reşadi̇ye', 'Sulusaray', 'Turhal', 'Yeşi̇lyurt', 'Zi̇le'],
    'Trabzon': ['Merkez', 'Akçaabat', 'Arakli', 'Arsi̇n', 'Beşi̇kdüzü', 'Dernekpazari', 'Düzköy', 'Hayrat', 'Köprübaşi', 'Maçka', 'Of', 'Ortahi̇sar', 'Sürmene', 'Tonya', 'Vakfikebi̇r', 'Yomra', 'Çarşibaşi', 'Çaykara', 'Şalpazari'],
    'Tunceli̇': ['Merkez', 'Hozat', 'Mazgi̇rt', 'Nazimi̇ye', 'Ovacik', 'Pertek', 'Pülümür', 'Çemi̇şgezek'],
    'Uşak': ['Merkez', 'Banaz', 'Eşme', 'Karahalli', 'Si̇vasli', 'Ulubey'],
    'Van': ['Merkez', 'Bahçesaray', 'Başkale', 'Edremi̇t', 'Erci̇ş', 'Gevaş', 'Gürpinar', 'Muradi̇ye', 'Saray', 'Tuşba', 'Çaldiran', 'Çatak', 'Özalp', 'İpekyolu'],
    'Yalova': ['Merkez', 'Altinova', 'Armutlu', 'Termal', 'Çinarcik', 'Çi̇ftli̇kköy'],
    'Yozgat': ['Merkez', 'Akdağmadeni̇', 'Aydincik', 'Boğazliyan', 'Kadişehri̇', 'Saraykent', 'Sarikaya', 'Sorgun', 'Yeni̇fakili', 'Yerköy', 'Çandir', 'Çayiralan', 'Çekerek', 'Şefaatli̇'],
    'Zonguldak': ['Merkez', 'Alapli', 'Devrek', 'Ereğli̇', 'Gökçebey', 'Ki̇li̇mli̇', 'Çaycuma'],
    'Çanakkale': ['Merkez', 'Ayvacik', 'Bayrami̇ç', 'Bi̇ga', 'Bozcaada', 'Eceabat', 'Ezi̇ne', 'Geli̇bolu', 'Lapseki̇', 'Yeni̇ce', 'Çan', 'İmroz'],
    'Çankiri': ['Merkez', 'Atkaracalar', 'Bayramören', 'Eldi̇van', 'Ilgaz', 'Kizilirmak', 'Korgun', 'Kurşunlu', 'Orta', 'Yaprakli', 'Çerkeş', 'Şabanözü'],
    'Çorum': ['Merkez', 'Alaca', 'Bayat', 'Boğazkale', 'Dodurga', 'Kargi', 'Laçi̇n', 'Meci̇tözü', 'Ortaköy', 'Osmancik', 'Oğuzlar', 'Sungurlu', 'Uğurludağ', 'İski̇li̇p'],
    'İstanbul': ['Merkez', 'Adalar', 'Arnavutköy', 'Ataşehi̇r', 'Avcilar', 'Bahçeli̇evler', 'Bakirköy', 'Bayrampaşa', 'Bağcilar', 'Başakşehi̇r', 'Beykoz', 'Beyli̇kdüzü', 'Beyoğlu', 'Beşi̇ktaş', 'Büyükçekmece', 'Esenler', 'Esenyurt', 'Eyüp', 'Fati̇h', 'Gazi̇osmanpaşa', 'Güngören', 'Kadiköy', 'Kartal', 'Kağithane', 'Küçükçekmece', 'Maltepe', 'Pendi̇k', 'Sancaktepe', 'Sariyer', 'Si̇li̇vri̇', 'Sultanbeyli̇', 'Sultangazi̇', 'Tuzla', 'Zeyti̇nburnu', 'Çatalca', 'Çekmeköy', 'Ümrani̇ye', 'Üsküdar', 'Şi̇le', 'Şi̇şli̇'],
    'İzmi̇r': ['Merkez', 'Ali̇ağa', 'Balçova', 'Bayindir', 'Bayrakli', 'Bergama', 'Beydağ', 'Bornova', 'Buca', 'Di̇ki̇li̇', 'Foça', 'Gazi̇emi̇r', 'Güzelbahçe', 'Karabağlar', 'Karaburun', 'Karşiyaka', 'Kemalpaşa', 'Kinik', 'Ki̇raz', 'Konak', 'Menderes', 'Menemen', 'Narlidere', 'Seferi̇hi̇sar', 'Selçuk', 'Ti̇re', 'Torbali', 'Urla', 'Çeşme', 'Çi̇ğli̇', 'Ödemi̇ş'],
    'Şanliurfa': ['Merkez', 'Akçakale', 'Bi̇reci̇k', 'Bozova', 'Ceylanpinar', 'Eyyübi̇ye', 'Halfeti̇', 'Hali̇li̇ye', 'Harran', 'Hi̇lvan', 'Karaköprü', 'Si̇verek', 'Suruç', 'Vi̇ranşehi̇r'],
    'Şirnak': ['Merkez', 'Beytüşşebap', 'Ci̇zre', 'Güçlükonak', 'Si̇lopi̇', 'Uludere', 'İdi̇l'],
  };
}
